INSERT INTO CAT(ID, NAME, AGE, SEX, OWNER) VALUES (99, 'Fluffy', 5, 'MALE', 'Sarah');
INSERT INTO CAT(ID, NAME, AGE, SEX, OWNER) VALUES (100, 'Oliver', 12, 'MALE', 'Sarah');
INSERT INTO CAT(ID, NAME, AGE, SEX, OWNER) VALUES (101, 'Luna', 7, 'FEMALE', 'Sarah');
INSERT INTO CAT(ID, NAME, AGE, SEX, OWNER) VALUES (102, 'Pumpkin', 10, 'FEMALE', 'Kumar');